lst = [1, 2, 3, 2, 4, 5, 6]
print("Original List:", lst)
lst.append(70)
print("After append(70):", lst)
lst.insert(2, 15)
print("After insert(2, 15):", lst)
copy_list = lst.copy()
print("Copied List:", copy_list)
lst.extend([80, 90])
print("After extend([80, 90]):", lst)
count_20 = lst.count(20)
print("Count of 20 in list:", count_20)
lst.remove(15)
print("After remove(15):", lst)
popped_item = lst.pop(3)
print(f"After pop(3): {lst} (Removed element: {popped_item})")
lst.sort()
print("After sort():", lst)
lst.reverse()
print("After reverse():", lst)
lst.clear()
print("After clear():", lst)
